version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://localhost:27017  # Update this if your FastAPI uses env vars
