version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 10s
      retries: 5

  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy